import { useState } from "react";
import { Layout } from "antd";
import Head from "next/head";
import HomeFooter from "../Footer/HomeFooter";
import HomeMenu from "../menues/homeMenu";
import HomeHeader from "../shared/homeHeader";
import TopAdsBanner from "../shared/TopAdsBanner";

const { Content } = Layout;

const HomeLayout = ({ children, title }) => {
    const [visible, setVisible] = useState(false);
    const [showTop, setShowTop] = useState(true);

    const handleShoeAds = (show) => {
        console.log("showTop", show);
        setShowTop(show);
    };

    return (
        <Layout>
            <Head>
                <title>{title || "Othoba Mart"}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* top ads banner */}
            {showTop && (
                <TopAdsBanner
                    promoCode={"Black Friday 101"}
                    promoValue={"19%"}
                    buttonSlug={"/shop"}
                    handleShoeAds={handleShoeAds}
                />
            )}

            {/* home header navigation */}
            <HomeHeader />

            {/* Top menu */}
            <div className="nav-menu-home">
                <div className="container mx-auto hidden lg:block">
                    <HomeMenu visible={visible} setVisible={setVisible} />
                </div>
            </div>

            <Content style={{ minHeight: "90vh", backgroundColor: "white" }}>
                <div className="container mx-auto px-3">{children}</div>
            </Content>
            <footer className="bg-white">
                <HomeFooter />
            </footer>
        </Layout>
    );
};

export default HomeLayout;
